cc_test(
    name = "binary_tree_test",
    srcs = ["binary_tree_test.cpp"],
    copts = ["-Iexternal/gtest/include -Idsa/include"],
    deps = [
        "@googletest//:gtest",
        "//dsa:dsa",
    ],
)