sudo: required

language: cpp
compiler: g++

matrix:
  include:
    # Job1: This is the job of building project on ubuntu linux os.
    - os: linux
      dist: trusty
      before_install:
        - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
        - sudo apt-get update -qq
      install:
        - sudo apt-get install -qq g++-7
        - export CXX="g++-7"
      script:
        - bash ./build.sh
        - ./build/test/demo_test
        - ./build/test/binary_tree_test
      notifications:
        email: true

      # Job2: This is the job of building project on os X.

      # Job3: checking style
