sudo: required

language: cpp
compiler: g++

matrix:
  include:
    # Job1: This is the job of building project and running all unit tests on ubuntu linux os.
    - os: linux
      dist: trusty
      before_install:
        - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
        - sudo apt-get update -qq
      install:
        - sudo apt-get install -qq g++-8
        - export CXX="g++-8"
        - export CC="gcc-8"
      script:
        - bash ./build.sh
        - cd build && make test
      notifications:
        email: true

      # Job2: This is the job of building project on os X.

      # Job3: checking style
