cc_binary(
    name = "binary_tree_example",
    srcs = ["binary_tree_example.cpp"],
    copts = ["-Idsa/include"],
    deps = ["//dsa:dsa"],
)

cc_binary(
    name = "binary_search_tree_example",
    srcs = ["binary_search_tree_example.cpp"],
    copts = ["-Idsa/include"],
    deps = ["//dsa:dsa"],
)

cc_binary(
    name = "red_black_tree_example",
    srcs = ["red_black_tree_example.cpp"],
    copts = ["-Idsa/include"],
    deps = ["//dsa:dsa"],
)
