binary_search_tree_test: binary_search_tree_test.cpp binary_search_tree.h ../binary-tree/binary_tree.h
	g++ -g -std=c++17 -o $@ -I.. binary_search_tree_test.cpp

clean:
	rm -r binary_search_tree_test binary_search_tree_test.dSYM

.PHONY: clean
